server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
javatechstack:
  rabbitmq:
    exchange: serviceregistry.direct
    routingkey: serviceregistry.routingkey
    queue: serviceregistry.queue
