server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
javatechstack:
  rabbitmq:
    queue: serviceregistry.queue

spring:
  application:
    name: order-client
  data:
    mongodb:
      database: test
      port: 27017
      host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

