server:
  port: 8083
spring:
  application:
    name: order-client
  data:
    mongodb:
      database: test
      port: 27017
      host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
javatechstack:
  rabbitmq:
    exchange: javatechstack.direct
    routingkey: javatechstack.routingkey
    queue: javatechstack.queue