server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: warehouse-client
  data:
    mongodb:
      database: test
      port: 27017
      host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

javatechstack:
  rabbitmq:
    queue: serviceregistry.queue
